DROP SEQUENCE "SEQ_CTRL_USUARIO";
/

DROP SEQUENCE "SEQ_CTRL_ADMINISTRADOR";
/

DROP SEQUENCE "SEQ_CTRL_MARCACION";
/

DROP TABLE "CTRL_ADMINISTRADOR";
/

DROP TABLE "CTRL_MARCACION";
/

DROP TABLE "CTRL_USUARIO";
/

DROP VIEW "CTRL_VIEW_MARCACION";
/

CREATE SEQUENCE "SEQ_CTRL_ADMINISTRADOR" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20;
/

CREATE SEQUENCE "SEQ_CTRL_USUARIO" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20;
/

CREATE SEQUENCE "SEQ_CTRL_MARCACION" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20;
/

CREATE TABLE "CTRL_ADMINISTRADOR" (
    "ID"           NUMBER
        NOT NULL ENABLE,
    "USUARIO_ID"   NUMBER
        NOT NULL ENABLE,
    "ROLE"         VARCHAR2(60 BYTE),
    CONSTRAINT "CTRL_ADMINISTRADOR_PK" PRIMARY KEY ( "ID" )
);
/

CREATE TABLE "CTRL_USUARIO" (
    "ID"                    NUMBER
        NOT NULL ENABLE,
    "LOGIN"                 VARCHAR2(100 BYTE),
    "NOMBRE"                VARCHAR2(60 BYTE),
    "APELLIDOS"             VARCHAR2(100 BYTE),
    "NIT"                   VARCHAR2(20 BYTE),
    "EMAIL"                 VARCHAR2(100 BYTE),
    "PERTENECE"             VARCHAR2(60 BYTE),
    "AUTH_TOKEN"            VARCHAR2(250 BYTE),
    "AUTH_TOKEN_USE_DATE"   DATE,
    CONSTRAINT "CTRL_USUARIO_PK" PRIMARY KEY ( "ID" )
);
/

CREATE TABLE "CTRL_MARCACION" (
    "ID"           NUMBER
        NOT NULL ENABLE,
    "USUARIO_ID"   NUMBER
        NOT NULL ENABLE,
    "HOSTNAME"     VARCHAR2(100 BYTE),
    "MARCACION"    DATE DEFAULT SYSDATE
        NOT NULL ENABLE,
    CONSTRAINT "CTRL_MARCACION_PK" PRIMARY KEY ( "ID" )
);
/

CREATE VIEW "CTRL_VIEW_MARCACION" AS
    SELECT
        u."ID" AS usuario_id,
        substr(u."NOMBRE"
                 || ' '
                 || u."APELLIDOS",1,60) AS nombre,
        u."NIT",
        m."ID" AS id,
        m."MARCACION",
        TO_CHAR(m."MARCACION",'DD/MM/YYYY') sfecha,
        TO_CHAR(m."MARCACION",'HH24:MI') shora
    FROM
        "CTRL_USUARIO" u,
        "CTRL_MARCACION" m
    WHERE
        u."ID" = m."USUARIO_ID"
        AND NOT EXISTS (
            SELECT
                NULL
            FROM
                "CTRL_ADMINISTRADOR" a
            WHERE
                a."USUARIO_ID" = u."ID"
        );
/

ALTER TABLE "CTRL_MARCACION"
    ADD CONSTRAINT "CTRL_MARCACION_REF01" FOREIGN KEY ( "USUARIO_ID" )
        REFERENCES "CTRL_USUARIO" ( "ID" );
/

ALTER TABLE "CTRL_ADMINISTRADOR"
    ADD CONSTRAINT "CTRL_ADMINISTRADOR_REF01" FOREIGN KEY ( "USUARIO_ID" )
        REFERENCES "CTRL_USUARIO" ( "ID" );
/

    CREATE INDEX "IDX_CTRL_USUARIO_LOGIN" ON
        "CTRL_USUARIO" (
            "LOGIN"
        );
/

    CREATE INDEX "IDX_CTRL_USUARIO_NIT" ON
        "CTRL_USUARIO" (
            "NIT"
        );
/

    CREATE INDEX "IDX_CTRL_USUARIO_EMAIL" ON
        "CTRL_USUARIO" (
            "EMAIL"
        );
/

    CREATE INDEX "IDX_CTRL_USUARIO_PERTENECE" ON
        "CTRL_USUARIO" (
            "PERTENECE"
        );
/

    CREATE INDEX "IDX_CTRL_USUARIO_AUTHTKN" ON
        "CTRL_USUARIO" (
            "AUTH_TOKEN"
        );
/

    CREATE INDEX "IDX_CTRL_USUARIO_AUTHTKNDTE" ON
        "CTRL_USUARIO" (
            "AUTH_TOKEN_USE_DATE"
        );
/

    CREATE INDEX "IDX_CTRL_USUARIO_COMPUESTO" ON
        "CTRL_USUARIO" (
            "LOGIN",
            "NIT",
            "EMAIL"
        );
/

    CREATE INDEX "IDX_CTRL_MARCACION_MARCACION" ON
        "CTRL_MARCACION" (
            "MARCACION"
        );
/